// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli

import (
	"github.com/protoflow-labs/protoflow/pkg/api"
	"github.com/protoflow-labs/protoflow/pkg/bucket"
	"github.com/protoflow-labs/protoflow/pkg/config"
	"github.com/protoflow-labs/protoflow/pkg/db"
	"github.com/protoflow-labs/protoflow/pkg/generate"
	"github.com/protoflow-labs/protoflow/pkg/log"
	"github.com/protoflow-labs/protoflow/pkg/openai"
	"github.com/protoflow-labs/protoflow/pkg/project"
	"github.com/protoflow-labs/protoflow/pkg/store"
	"github.com/protoflow-labs/protoflow/pkg/workflow"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func Wire(cacheConfig bucket.Config) (*cli.App, error) {
	localBucket, err := bucket.NewUserCache(cacheConfig)
	if err != nil {
		return nil, err
	}
	provider, err := config.NewProvider(localBucket)
	if err != nil {
		return nil, err
	}
	apiConfig, err := api.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	dbConfig, err := db.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.NewGormDB(dbConfig, localBucket)
	if err != nil {
		return nil, err
	}
	projectStore, err := store.NewDBStore(gormDB)
	if err != nil {
		return nil, err
	}
	openaiConfig, err := openai.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	openAIQAClient, err := openai.NewOpenAIQAClient(openaiConfig)
	if err != nil {
		return nil, err
	}
	chatServer := openai.NewChat(openAIQAClient)
	genProject, err := project.NewDefaultProject(localBucket)
	if err != nil {
		return nil, err
	}
	workflowManager := workflow.NewWorkflowManager()
	managerBuilder := workflow.NewManagerBuilder(workflowManager)
	service, err := project.NewService(projectStore, localBucket, chatServer, genProject, managerBuilder, workflowManager)
	if err != nil {
		return nil, err
	}
	generateConfig, err := generate.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	generateService, err := generate.NewService(generateConfig, projectStore)
	if err != nil {
		return nil, err
	}
	httpServer, err := api.NewHTTPServer(apiConfig, service, generateService)
	if err != nil {
		return nil, err
	}
	logConfig, err := log.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	logLog := log.NewLog(logConfig)
	app := New(httpServer, service, logLog)
	return app, nil
}
