// @generated by protoc-gen-es v1.5.1 with parameter "target=ts"
// @generated from file ai.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message GeneratedCode
 */
export class GeneratedCode extends Message<GeneratedCode> {
  /**
   * Code that has been generated.
   *
   * @generated from field: string code = 1;
   */
  code = "";

  constructor(data?: PartialMessage<GeneratedCode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "GeneratedCode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeneratedCode {
    return new GeneratedCode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeneratedCode {
    return new GeneratedCode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeneratedCode {
    return new GeneratedCode().fromJsonString(jsonString, options);
  }

  static equals(a: GeneratedCode | PlainMessage<GeneratedCode> | undefined, b: GeneratedCode | PlainMessage<GeneratedCode> | undefined): boolean {
    return proto3.util.equals(GeneratedCode, a, b);
  }
}

