// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file generate.proto (package generate, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GenerateImplementationRequest, GenerateImplementationResponse, GenerateRequest, GenerateResponse, InferNodeTypeRequest, InfertNodeTypeResponse } from "./generate_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service generate.GenerateService
 */
export const GenerateService = {
  typeName: "generate.GenerateService",
  methods: {
    /**
     * @generated from rpc generate.GenerateService.Generate
     */
    generate: {
      name: "Generate",
      I: GenerateRequest,
      O: GenerateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc generate.GenerateService.GenerateImplementation
     */
    generateImplementation: {
      name: "GenerateImplementation",
      I: GenerateImplementationRequest,
      O: GenerateImplementationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc generate.GenerateService.InferNodeType
     */
    inferNodeType: {
      name: "InferNodeType",
      I: InferNodeTypeRequest,
      O: InfertNodeTypeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

