// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file openai.proto (package openai, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PromptRequest, PromptResponse } from "./openai_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service openai.OpenAIService
 */
export const OpenAIService = {
  typeName: "openai.OpenAIService",
  methods: {
    /**
     * @generated from rpc openai.OpenAIService.Prompt
     */
    prompt: {
      name: "Prompt",
      I: PromptRequest,
      O: PromptResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

