// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file resource.proto (package resource, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Block } from "./block_pb.js";

/**
 * @generated from enum resource.Runtime
 */
export enum Runtime {
  /**
   * @generated from enum value: NODE = 0;
   */
  NODE = 0,

  /**
   * @generated from enum value: GO = 1;
   */
  GO = 1,

  /**
   * @generated from enum value: PYTHON = 2;
   */
  PYTHON = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Runtime)
proto3.util.setEnumType(Runtime, "resource.Runtime", [
  { no: 0, name: "NODE" },
  { no: 1, name: "GO" },
  { no: 2, name: "PYTHON" },
]);

/**
 * @generated from message resource.Resource
 */
export class Resource extends Message<Resource> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from oneof resource.Resource.type
   */
  type: {
    /**
     * @generated from field: resource.GRPCService grpc_service = 3;
     */
    value: GRPCService;
    case: "grpcService";
  } | {
    /**
     * @generated from field: resource.RESTService rest_service = 4;
     */
    value: RESTService;
    case: "restService";
  } | {
    /**
     * @generated from field: resource.Docstore docstore = 5;
     */
    value: Docstore;
    case: "docstore";
  } | {
    /**
     * @generated from field: resource.Blobstore blobstore = 6;
     */
    value: Blobstore;
    case: "blobstore";
  } | {
    /**
     * @generated from field: resource.LanguageService language_service = 7;
     */
    value: LanguageService;
    case: "languageService";
  } | { case: undefined; value?: undefined } = { case: undefined };

  /**
   * @generated from field: repeated block.Block blocks = 8;
   */
  blocks: Block[] = [];

  constructor(data?: PartialMessage<Resource>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "resource.Resource";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "grpc_service", kind: "message", T: GRPCService, oneof: "type" },
    { no: 4, name: "rest_service", kind: "message", T: RESTService, oneof: "type" },
    { no: 5, name: "docstore", kind: "message", T: Docstore, oneof: "type" },
    { no: 6, name: "blobstore", kind: "message", T: Blobstore, oneof: "type" },
    { no: 7, name: "language_service", kind: "message", T: LanguageService, oneof: "type" },
    { no: 8, name: "blocks", kind: "message", T: Block, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Resource {
    return new Resource().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Resource {
    return new Resource().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Resource {
    return new Resource().fromJsonString(jsonString, options);
  }

  static equals(a: Resource | PlainMessage<Resource> | undefined, b: Resource | PlainMessage<Resource> | undefined): boolean {
    return proto3.util.equals(Resource, a, b);
  }
}

/**
 * @generated from message resource.LanguageService
 */
export class LanguageService extends Message<LanguageService> {
  /**
   * @generated from field: resource.Runtime runtime = 1;
   */
  runtime = Runtime.NODE;

  /**
   * @generated from field: resource.GRPCService grpc = 2;
   */
  grpc?: GRPCService;

  constructor(data?: PartialMessage<LanguageService>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "resource.LanguageService";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "runtime", kind: "enum", T: proto3.getEnumType(Runtime) },
    { no: 2, name: "grpc", kind: "message", T: GRPCService },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LanguageService {
    return new LanguageService().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LanguageService {
    return new LanguageService().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LanguageService {
    return new LanguageService().fromJsonString(jsonString, options);
  }

  static equals(a: LanguageService | PlainMessage<LanguageService> | undefined, b: LanguageService | PlainMessage<LanguageService> | undefined): boolean {
    return proto3.util.equals(LanguageService, a, b);
  }
}

/**
 * @generated from message resource.GRPCService
 */
export class GRPCService extends Message<GRPCService> {
  /**
   * @generated from field: string host = 1;
   */
  host = "";

  constructor(data?: PartialMessage<GRPCService>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "resource.GRPCService";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "host", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GRPCService {
    return new GRPCService().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GRPCService {
    return new GRPCService().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GRPCService {
    return new GRPCService().fromJsonString(jsonString, options);
  }

  static equals(a: GRPCService | PlainMessage<GRPCService> | undefined, b: GRPCService | PlainMessage<GRPCService> | undefined): boolean {
    return proto3.util.equals(GRPCService, a, b);
  }
}

/**
 * @generated from message resource.RESTService
 */
export class RESTService extends Message<RESTService> {
  /**
   * @generated from field: string base_url = 1;
   */
  baseUrl = "";

  constructor(data?: PartialMessage<RESTService>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "resource.RESTService";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RESTService {
    return new RESTService().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RESTService {
    return new RESTService().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RESTService {
    return new RESTService().fromJsonString(jsonString, options);
  }

  static equals(a: RESTService | PlainMessage<RESTService> | undefined, b: RESTService | PlainMessage<RESTService> | undefined): boolean {
    return proto3.util.equals(RESTService, a, b);
  }
}

/**
 * @generated from message resource.Docstore
 */
export class Docstore extends Message<Docstore> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  constructor(data?: PartialMessage<Docstore>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "resource.Docstore";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Docstore {
    return new Docstore().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Docstore {
    return new Docstore().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Docstore {
    return new Docstore().fromJsonString(jsonString, options);
  }

  static equals(a: Docstore | PlainMessage<Docstore> | undefined, b: Docstore | PlainMessage<Docstore> | undefined): boolean {
    return proto3.util.equals(Docstore, a, b);
  }
}

/**
 * @generated from message resource.Blobstore
 */
export class Blobstore extends Message<Blobstore> {
  /**
   * @generated from field: string url = 1;
   */
  url = "";

  constructor(data?: PartialMessage<Blobstore>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "resource.Blobstore";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Blobstore {
    return new Blobstore().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Blobstore {
    return new Blobstore().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Blobstore {
    return new Blobstore().fromJsonString(jsonString, options);
  }

  static equals(a: Blobstore | PlainMessage<Blobstore> | undefined, b: Blobstore | PlainMessage<Blobstore> | undefined): boolean {
    return proto3.util.equals(Blobstore, a, b);
  }
}

