// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file project.proto (package project, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateProjectRequest, CreateProjectResponse, CreateResourceRequest, CreateResourceResponse, DeleteProjectRequest, DeleteProjectResponse, GetProjectRequest, GetProjectResponse, GetProjectsRequest, GetProjectsResponse, GetResourcesRequest, GetResourcesResponse, RunBlockRequest, RunOutput, RunWorkflowRequest, SaveProjectRequest, SaveProjectResponse } from "./project_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service project.ProjectService
 */
export const ProjectService = {
  typeName: "project.ProjectService",
  methods: {
    /**
     * @generated from rpc project.ProjectService.GetProject
     */
    getProject: {
      name: "GetProject",
      I: GetProjectRequest,
      O: GetProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.GetProjects
     */
    getProjects: {
      name: "GetProjects",
      I: GetProjectsRequest,
      O: GetProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: CreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.DeleteProject
     */
    deleteProject: {
      name: "DeleteProject",
      I: DeleteProjectRequest,
      O: DeleteProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.GetResources
     */
    getResources: {
      name: "GetResources",
      I: GetResourcesRequest,
      O: GetResourcesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.SaveProject
     */
    saveProject: {
      name: "SaveProject",
      I: SaveProjectRequest,
      O: SaveProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.CreateResource
     */
    createResource: {
      name: "CreateResource",
      I: CreateResourceRequest,
      O: CreateResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.RunWorklow
     */
    runWorklow: {
      name: "RunWorklow",
      I: RunWorkflowRequest,
      O: RunOutput,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.RunBlock
     */
    runBlock: {
      name: "RunBlock",
      I: RunBlockRequest,
      O: RunOutput,
      kind: MethodKind.Unary,
    },
  }
} as const;

