// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file project.proto (package project, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddBlockRequest, AddBlockResponse, AddEdgeRequest, AddEdgeResponse, CreateProjectRequest, CreateProjectResponse, DeleteProjectRequest, DeleteProjectResponse, GetBlocksRequest, GetBlocksResponse, GetEdgesRequest, GetEdgesResponse, GetProjectRequest, GetProjectResponse, GetProjectsRequest, GetProjectsResponse, GetResourcesRequest, GetResourcesResponse, RemoveBlockRequest, RemoveBlockResponse, RemoveEdgeRequest, RemoveEdgeResponse, UpdateBlockRequest, UpdateBlockResponse } from "./project_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service project.ProjectService
 */
export const ProjectService = {
  typeName: "project.ProjectService",
  methods: {
    /**
     * @generated from rpc project.ProjectService.GetProject
     */
    getProject: {
      name: "GetProject",
      I: GetProjectRequest,
      O: GetProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.GetProjects
     */
    getProjects: {
      name: "GetProjects",
      I: GetProjectsRequest,
      O: GetProjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.CreateProject
     */
    createProject: {
      name: "CreateProject",
      I: CreateProjectRequest,
      O: CreateProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.DeleteProject
     */
    deleteProject: {
      name: "DeleteProject",
      I: DeleteProjectRequest,
      O: DeleteProjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.GetResources
     */
    getResources: {
      name: "GetResources",
      I: GetResourcesRequest,
      O: GetResourcesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.GetBlocks
     */
    getBlocks: {
      name: "GetBlocks",
      I: GetBlocksRequest,
      O: GetBlocksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.AddBlock
     */
    addBlock: {
      name: "AddBlock",
      I: AddBlockRequest,
      O: AddBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.RemoveBlock
     */
    removeBlock: {
      name: "RemoveBlock",
      I: RemoveBlockRequest,
      O: RemoveBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.UpdateBlock
     */
    updateBlock: {
      name: "UpdateBlock",
      I: UpdateBlockRequest,
      O: UpdateBlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.GetEdges
     */
    getEdges: {
      name: "GetEdges",
      I: GetEdgesRequest,
      O: GetEdgesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.AddEdge
     */
    addEdge: {
      name: "AddEdge",
      I: AddEdgeRequest,
      O: AddEdgeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc project.ProjectService.RemoveEdge
     */
    removeEdge: {
      name: "RemoveEdge",
      I: RemoveEdgeRequest,
      O: RemoveEdgeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

