// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file workflow.proto (package workflow, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ID, Run, Workflow, WorkflowEntrypoint } from "./workflow_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service workflow.Manager
 */
export const Manager = {
  typeName: "workflow.Manager",
  methods: {
    /**
     * @generated from rpc workflow.Manager.CreateWorkflow
     */
    createWorkflow: {
      name: "CreateWorkflow",
      I: Workflow,
      O: ID,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc workflow.Manager.StartWorkflow
     */
    startWorkflow: {
      name: "StartWorkflow",
      I: WorkflowEntrypoint,
      O: Run,
      kind: MethodKind.Unary,
    },
  }
} as const;

